DROP TABLE IF EXISTS Attendance_History;
DROP TABLE IF EXISTS List_of_Subscribed_Events;
DROP TABLE IF EXISTS Waitlist;
DROP TABLE IF EXISTS Payment_method;
DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS Concert;
DROP TABLE IF EXISTS Webinar;
DROP TABLE IF EXISTS Conference;
DROP TABLE IF EXISTS Workshop;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS Organization;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Passwords;

